name: amogus
main: xyz.awexxx.App
description: MCImpos - Among Us, but in Minecraft
version: 0.1
website: https://github.com/awexthedev/SheepPenetrator
depend: [LuckPerms]
authors: [awex]
api-version: 1.18
commands:
  startg:
    description: Start the game.
    usage: /startg
    permission: amogus.startgame
    permission-message: You do not have permission to use this command.
  endg:
    description: Stop the game.
    usage: /endg
    permission: amogus.endgame
    permission-message: You do not have permission to use this command.
  submit:
    description: Open a GUI to submit your vote.
    usage: /submit
    permission: amogus.submit
    permission-message: You do not have permission to use this command.
  check:
    description: Check all votes to see who has the most.
    usage: /check
    permission: amogus.check
    permission-message: You do not have permission to use this command.