name: mcimpos
main: dev.thatalex.main.App
description: MCImpos - Among Us, but in Minecraft
version: 0.2.0
website: https://github.com/awexthedev/mcimpos
authors: [awex]
api-version: 1.18
commands:
  startg:
    description: Start the game.
    usage: /startg
    permission: amogus.startgame
    permission-message: You do not have permission to use this command.
  endg:
    description: Stop the game.
    usage: /endg
    permission: amogus.endgame
    permission-message: You do not have permission to use this command.
  submit:
    description: Open a GUI to submit your vote.
    usage: /submit
    permission: amogus.submit
    permission-message: You do not have permission to use this command.
  sabotage:
    description: As an impostor, sabotage other players.
    usage: /sabotage
    permission: amogus.sabotage
    permission-message: You do not have permission to use this command.
  tasks:
    description: View your current tasks.
    usage: /tasks
    permission: amogus.sabotage
    permission-message: You do not have permission to use this command.
  imp:
    description: View your current tasks.
    usage: /imp
    permission: amogus.sabotage
    permission-message: You do not have permission to use this command.