name: mcimpos
main: xyz.awexxx.App
description: MCImpos - Among Us, but in Minecraft
version: 0.1.7
website: https://github.com/awexthedev/SheepPenetrator
depend: [LuckPerms]
authors: [awex]
api-version: 1.18
commands:
  startg:
    description: Start the game.
    usage: /startg
    permission: amogus.startgame
    permission-message: You do not have permission to use this command.
  endg:
    description: Stop the game.
    usage: /endg
    permission: amogus.endgame
    permission-message: You do not have permission to use this command.
  submit:
    description: Open a GUI to submit your vote.
    usage: /submit
    permission: amogus.submit
    permission-message: You do not have permission to use this command.
  sabotage:
    description: As an impostor, sabotage other players.
    usage: /sabotage
    permission: amogus.sabotage
    permission-message: You do not have permission to use this command.